export const CAREERS = [
  "Doctor",
  "Nurse",
  "Surgeon",
  "Dentist",
  "Pharmacist",
  "Physiotherapist",
  "Veterinarian",
  "Medical Researcher",
  "Psychologist",
  "Clinical Psychologist",
  "Occupational Therapist",
  "Public Health Specialist",
  "Radiologist",
  "Nutritionist",
  "Paramedic",
  "Scientist",
  "Data Scientist",
  "Software Engineer",
  "AI/ML Engineer",
  "Web Developer",
  "Mobile App Developer",
  "Blockchain Developer",
  "Cybersecurity Specialist",
  "Robotics Engineer",
  "Biotechnologist",
  "Geneticist",
  "Environmental Scientist",
  "Astronomer",
  "Mathematician",
  "Physicist",
  "Chemist",
  "Researcher",
  "Civil Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Electronics Engineer",
  "Computer Engineer",
  "Chemical Engineer",
  "Architect",
  "Interior Designer",
  "Urban Planner",
  "Industrial Engineer",
  "Automobile Engineer",
  "Structural Engineer",
  "Chartered Accountant",
  "Financial Analyst",
  "Investment Banker",
  "Economist",
  "Business Analyst",
  "Entrepreneur",
  "Marketing Manager",
  "Sales Executive",
  "Human Resources Manager",
  "Management Consultant",
  "MBA",
  "Operations Manager",
  "Supply Chain Manager",
  "Lawyer",
  "Judge",
  "Legal Advisor",
  "Company Secretary",
  "IAS Officer",
  "IPS Officer",
  "IRS Officer",
  "Civil Services Officer",
  "Diplomat",
  "Politician",
  "Policy Analyst",
  "Teacher",
  "Professor",
  "Lecturer",
  "Educational Consultant",
  "Tutor",
  "Librarian",
  "Special Education Teacher",
  "Journalist",
  "Content Writer",
  "Editor",
  "Copywriter",
  "Public Relations Specialist",
  "Social Media Manager",
  "Digital Marketer",
  "Video Producer",
  "Film Director",
  "Actor",
  "Animator",
  "Graphic Designer",
  "Fashion Designer",
  "Photographer",
  "Event Manager",
  "Travel Blogger",
  "Illustrator",
  "Videographer",
  "Game Designer",
  "UX/UI Designer",
  "Sound Engineer",
  "Music Composer",
  "Pilot",
  "Air Traffic Controller",
  "Flight Attendant",
  "Maritime Officer",
  "Logistics Manager",
  "Transport Planner",
  "Athlete",
  "Fitness Trainer",
  "Yoga Instructor",
  "Sports Coach",
  "Sports Psychologist",
  "Hotel Manager",
  "Chef",
  "Tour Guide",
  "Travel Consultant",
  "Event Planner",
  "AI Specialist",
  "Robotics Engineer",
  "Drone Operator",
  "Game Developer",
  "VR/AR Developer",
  "Sustainability Consultant",
  "Renewable Energy Engineer",
  "Cryptocurrency Analyst",
  "NFT Designer",
  "Quantum Computing Researcher",
  "Social Worker",
  "NGO Worker",
  "Freelancer",
  "Consultant",
  "Motivational Speaker",
  "Author",
  "Musician",
  "Artist"
];
